name              "vagrant-lamp"
maintainer        "Rémi GATTAZ"
maintainer_email  "remi.gattaz@gmail.com"
description       "Entry point for installing and configuring a LAMP stack"
version           "0.1.0"
